OPENAI_API_KEY = "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"
LLAMA_CLOUD_API_KEY = "llx-sUQGIUw62uzj5yG0qo7JKjYH1QdQRWV7SxXCGEbPFk09a10K"
AWS_ACCESS_KEY = "AKIAYLZZKLOTYIXDAARY"
AWS_SECRET_KEY = "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"
AWS_REGION = "ap-south-1"
BUCKET_NAME = "aws-textract-bucket3"
